language: ruby
cache:
  - bundler
  - yarn
addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
env:
  global:
  - PGPORT=5433
  - PGUSER=travis
before_install:
  - nvm install 14
  - gem install bundler:2.2.5
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart
  - sleep 1
before_script:
  - bundle install --jobs=3 --retry=3
  - yarn
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:create
  - bundle exec rake db:structure:load
script:
  - echo "Install complete"