language: ruby
cache:
  - bundler
  - yarn
addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
before_install:
  - nvm install 14
  - gem install bundler:2.2.5
  - sudo sed -i -e 's/^#listen_addresses.*/listen_addresses = "*"/' /etc/postgresql/12/main/postgresql.conf
  - sudo sed -i -e 's/^port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
  - sudo systemctl restart postgresql@12-main
before_script:
  - bundle install --jobs=3 --retry=3
  - yarn
  - cp config/database.yml.sample config/database.yml
  - bundle exec rake db:create
  - bundle exec rake db:structure:load
script:
  - echo "Install complete"